version: '3.8'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    container_name: db_container

  backend:
    image: backend:latest
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=example
      - DB_HOST=db
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
    depends_on:
      - db

  frontend:
        image: frontend:latest
        ports:
            - 5000:5000
        environment:
            - API_URL=http://localhost:8000

  redis:
        image: redis:alpine
        ports:
            - "6379"

