version: '3.8'

services:

  db:
    image: postgres
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_container
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    image: backend:latest
    networks:
      - backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_DB_POSTGRES=db
      - BACKEND_DB_PASSWORD=example
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
    depends_on:
      - db

  frontend:
        image: frontend:latest
        ports:
            - "5000:5000"
        networks:
            - frontend
        environment:
            - API_URL=http://localhost:8000

  redis:
        image: redis:alpine
        ports:
            - "6379"
        networks:
            - backend

volumes:
  database:

networks:
  backend:
  frontend:
