version: '3.8'

services:
    redis:
        image: redis:alpine
        ports:
            - "6379"
        networks:
            - backend
    
    frontend:
        image: frontend:latest
        ports:
            - "5000:5000"
        environment:
            - "API_URL=http://localhost:8000"

    backend:
        image: backend:latest
        ports:
            - "8000:8000"
        networks:
            - backend
        environment:
            - "FRONT_URL=http://localhost:5000"
            - "REDIS=redis"

networks:
  backend:

