version: '3.8'

services:

  nginx-proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/logs:/var/log/postgresql
    ports:
      - 5432:5432

  backend:
    image: hulluukko/backend
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - BACKEND_DB_USERNAME=postgres
      - BACKEND_DB_PASSWORD=example
      - BACKEND_DB_NAME=example
      - BACKEND_DB_HOST=db
    depends_on:
      - db
      - redis

  frontend:
        image: hulluukko/frontend
        ports:
            - 5000:5000
        environment:
            - API_URL=http://localhost:8000

  redis:
        image: redis:alpine
        ports:
            - 6379:6379
